apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment-green
  labels:
    app: hello
    version: blue
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello
      version: v1
  template:
    metadata:
      labels:
        app: hello
        version: v1
    spec:
      containers:
      - name: hello-container
        image: europe-west1-docker.pkg.dev/qwiklabs-gcp-03-300a62073da1/my-repo/hello:v1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"